spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: transaction-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/transactions/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        
        - id: merchant-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/merchants/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
